---
title: "Combine Taxon Size data"
author: "Chih-Lin Wei"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


```{r}
library(ggplot2)
library(plyr)
library(doBy)
library(readxl)

large <- theme(legend.title = element_text(size=20),
        legend.text = element_text(size=20),
        strip.text=element_text(size=20),
        axis.title = element_text(size=20),
        axis.text.y = element_text(size=20),
        axis.text.x = element_text(size=20, angle=60, hjust=0.5))

rotate <- theme(axis.text.x = element_text(size=20, angle=60, hjust=0.5))

# dark theme for ggplot
dark <- theme(plot.background = element_rect(colour = 'NA', fill = 'gray10'),
        panel.background = element_rect(colour = 'NA', fill = 'transparent'),
        legend.background = element_rect(colour = 'NA', fill = 'transparent'),
        legend.title = element_text(colour = 'white', size=20),
        legend.text = element_text(colour = 'white', size=20),
        axis.title = element_text(colour = 'white', size=20),
        axis.text = element_text(colour = 'white', size=20),
        axis.ticks = element_line(colour = 'white'),
        panel.border = element_rect(fill = 'NA', colour = 'white'), 
        panel.grid.major = element_line(colour = 'gray30'),
        panel.grid.minor = element_line(colour = 'gray20'))
```

# Observed macrofauna body size

```{r, fig.width=10, fig.height=6}
col_types <- c("text", "text", "text", "numeric", "numeric", "text", "text", "text", "text", "text", "text", 
              "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "text")

mac <- NULL
for(i in 1:15){
  d <- read_excel("../excel/GPSC_macro_size_2020.01.08.xlsx", sheet=i, col_types=col_types)
  mac <- rbind(mac, d)
}
mac <- as.data.frame(mac)

depth <- read_excel("../excel/GPSC_macro_sorting_2019.12.16.xlsx", sheet=1)
mac <- cbind(depth[match(paste(mac$Cruise, mac$Station), paste(depth$Cruise, depth$Station)),], mac)
mac$Wt <- mac$Size*(1.13)

depth.bk <- c(200, 400, 600, 800, 1100, 2000, 3700)
depth.lab <- c("200-400", "400-600", "600-800", "800-1100", "1100-2000", "2000-3700")
mac$Depth.zone <- cut(mac$Depth, breaks=depth.bk, labels=depth.lab)

# Split the size data by polychaetes, nematods, harpacticoids, peracarids and others
Category <- as.character(mac$Taxon)
Category[Category=="Amphipoda"|Category=="Cumacea"|Category=="Isopoda"|Category=="Tanaidacea"] <- "Peracarida"
Category[Category=="Oligochaeta"|Category=="Nemertea"|Category=="Sipuncula"|Category=="Aplacophora"|Category=="Ostracoda"] <- "Others"

mac <- cbind(Category, mac)
mac <- subset(mac, Cruise=="OR1_1096"|Cruise=="OR1_1099"|Cruise=="OR1_1102"|Cruise=="OR1_1114"|Cruise=="OR1_1126")

# Size (complete specimen)
mac_s <- subset(mac, Condition=="C")

# Observed macrofauna sizes
ggplot(data=mac_s, 
       aes(x=log10(Wt), fill=Habitat, colour=Habitat))+
  geom_density(alpha=0.5)+
  facet_wrap(~Cruise, scales="free_y")+
  labs(y="Frequency", x=expression(Log[10]~body~size~(mg)))+
  theme_bw() %+replace% large %+replace% dark
```

```{r, fig.width=10, fig.height=6}
# Observed polychaete sizes
ggplot(data=subset(mac_s, Category=="Polychaeta"), 
       aes(x=log10(Wt), fill=Habitat, colour=Habitat))+
  geom_density(alpha=0.5)+
  facet_wrap(~Cruise, scales="free")+
  labs(y="Frequency", x=expression(Log[10]~body~size~(mg)))+
  theme_bw() %+replace% large %+replace% dark
```
No complete polychaete specimens in canyon during cruise 1099 and 1102.

# Observed meiofauna size distribution
100 nematodes were randomly selected to measured body size. 
```{r, fig.height=6, fig.width=10}
# Hapacticoid and others
col_types <- c("text", "text", "text", "numeric", "numeric", "numeric", "text","text", "text", "text", "text", "text", "text", "numeric", "numeric", "numeric", "numeric", "text")

mei <- NULL
for(i in 1:3){
  d <- as.data.frame(read_excel("../excel/GPSC_meio_size_2020.01.07.xlsx", sheet=i, col_types=col_types))
  mei <- rbind(mei, d)
}

# Get water depth
mei <- cbind(depth[match(paste(mei$Cruise, mei$Station), paste(depth$Cruise, depth$Station)),], mei)
mei$Wt <- mei$Size*(1.13)

depth.bk <- c(200, 400, 600, 800, 1100)
depth.lab <- c("200-400", "400-600", "600-800", "800-1100")
mei$Depth.zone <- cut(mei$Depth, breaks=depth.bk, labels=depth.lab)

# Split the size data by nematods, harpacticoids and others
Category <- as.character(mei$Taxon)
Category[Category!="Nematoda"&Category!="Harpacticoida"] <- "Others"
mei <- splitBy(~Category+Cruise+Station, cbind(Category, mei))
mei <- ldply(mei, .id=NULL)

ggplot(data=subset(mei, Cruise=="OR1_1114"|Cruise=="OR1_1126"), 
       aes(x=log(Wt), fill=Habitat, colour=Habitat))+
  geom_density(alpha=0.5)+
  facet_grid(Cruise~Category)+
  labs(y="Frequency", x=expression(Log~body~size~(mg~individual^-1)))+
  theme_bw()%+replace% large %+replace% dark
```

```{r}
save(mac, file="../data/mac.rda")
save(mei, file="../data/mei.rda")
```

