---
title: "Combind_multi_panel_figures"
author: "Chih-Lin Wei"
date: "2/26/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(patchwork)

large <- theme(legend.title = element_text(size=20),
        legend.text = element_text(size=20),
        axis.title = element_text(size=20),
        axis.text = element_text(size=20),
        title = element_text(size=20))

rotate <- theme(axis.text.x = element_text(size=20, angle=60, hjust=0.5))
no_strip <- theme(strip.background = element_rect(colour=NA, fill=NA),
                  strip.text = element_text(colour=NA))
no_legend <- theme(legend.position = "none")

# dark theme for ggplot
dark <- theme(plot.background = element_rect(colour = 'NA', fill = 'gray10'),
        panel.background = element_rect(colour = 'NA', fill = 'transparent'),
        legend.background = element_rect(colour = 'NA', fill = 'transparent'),
        legend.title = element_text(colour = 'white', size=20),
        legend.text = element_text(colour = 'white', size=20),
        axis.title = element_text(colour = 'white', size=20),
        axis.text = element_text(colour = 'white', size=20),
        axis.ticks = element_line(colour = 'white'),
        panel.border = element_rect(fill = 'NA', colour = 'white'), 
        panel.grid.major = element_line(colour = 'gray30'),
        panel.grid.minor = element_line(colour = 'gray20'))
```

```{r, fig.width=14, fig.height=5}
load("../rds/f3a.rds")
load("../rds/f3b.rds")

p1 <- f3a+labs(title="(A)")+no_legend + large
p2 <- f3b+labs(title="(B)") + large
p1+p2
```

```{r, fig.width=14, fig.height=10}
load("../rds/f4a.rds")
load("../rds/f4b.rds")
load("../rds/f4c.rds")
load("../rds/f4d.rds")

p1 <- f4a+labs(title="(A)")+no_legend + large
p2 <- f4b+labs(title="(B)") + large
p3 <- f4c+labs(title="(C)")+no_legend + large
p4 <- f4d+labs(title="(D)")+no_legend + large

(p1+p2)/(p3+p4)
```


```{r, fig.width=14, fig.height=10}
load("../rds/f5a.rds")
load("../rds/f5b.rds")
load("../rds/f5c.rds")
load("../rds/f5d.rds")

p1 <- f5a+labs(title="(A)")+no_legend + large
p2 <- f5b+labs(title="(B)") + large
p3 <- f5c+labs(title="(C)")+no_legend + large
p4 <- f5d+labs(title="(D)")+no_legend + large

(p1+p2)/(p3+p4)
```

```{r, fig.width=10, fig.height=12}
load("../rds/f2a.rds")
load("../rds/f2c.rds")
p1 <- f2a+no_legend+dark
p2 <- f2c+no_legend+dark
p3 <- f4c+no_legend+dark
p4 <- f4d+no_legend+dark
p5 <- f5c+no_legend+dark
p6 <- f5d+no_legend+dark

(p1+p2)/(p3+p4)/(p5+p6)
```

