---
title: "Environmental_variables"
author: "Chih-Lin Wei"
date: "3/1/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, fig.width=12, fig.height=12}
library(bbbs)
library(reshape2)
library(doBy)
library(ggplot2)
library(viridis)
env2 <- env[, c("Habitat", "Cruise", "Station", "Depth", "Speed.mean", "over20", "Temperature", "Salinity", "Density", "Oxygen", "fluorometer", "transmissometer", "Clay", "Silt", "Sand", "CN",  "TOC", "TN", "Porosity")]

names(env2)[5:19] <- c("Speed", "Over20", "Temperature", "Salin", "Density", "Oxygen", "Fluoro", "Trans", "Clay", "Silt", "Sand", "CN", "TOC", "TN", "Porosity")


se <- function(x)sd(x)/sqrt(length(x))
m <- summaryBy(Depth+Speed+Over20+Temperature+Salin+Density+Oxygen+Fluoro+Trans+Clay+Silt+Sand+CN+TOC+TN+Porosity~Habitat+Station, data=env2, FUN=mean, keep.names = TRUE)
s <-summaryBy(Depth+Speed+Over20+Temperature+Salin+Density+Oxygen+Fluoro+Trans+Clay+Silt+Sand+CN+TOC+TN+Porosity~Habitat+Station, data=env2, FUN=se, keep.names = TRUE)
m <- melt(m, , id.vars=c("Habitat", "Station", "Depth"), measure.vars=c("Speed", "Over20", "Temperature", "Salin", "Density", "Oxygen", "Fluoro", "Trans", "Clay", "Silt", "Sand", "CN", "TOC", "TN", "Porosity"), value.name = "mean")
s <- melt(s, , id.vars=c("Habitat", "Station", "Depth"), measure.vars=c("Speed", "Over20", "Temperature", "Salin", "Density", "Oxygen", "Fluoro", "Trans", "Clay", "Silt", "Sand", "CN", "TOC", "TN", "Porosity"), value.name = "se")


env3 <- cbind(m, se=s$se)

large <- theme(legend.title = element_text(size=20),
        legend.text = element_text(size=20),
        axis.title = element_text(size=20),
        axis.text = element_text(size=20),
        axis.text.x = element_text(angle = 60),
        strip.text= element_text(size=20))


ggplot(data=env3, aes(x=Depth, y=mean, ymin=mean-se, ymax=mean+se, shape=Habitat, linetype=Habitat, colour=Habitat))+
  geom_point(size=5, stroke=1.2)+
  geom_path(size=1)+
  scale_shape_manual(values=c(19,1))+
  geom_errorbar(linewidth=1)+
  #stat_smooth(method="lm", formula=y~x, alpha=0.2)+
  scale_linetype_manual(values=c(1,2))+
  scale_colour_manual(values=c("#f1a340", "#998ec3"))+
  labs(x="Depth (m)", y="")+
  facet_wrap(~variable, scales="free_y", ncol=3)+
  theme_bw()%+replace% large
```

```{r, fig.width=10, fig.height=8}
env4 <- subset(env3, variable!="Salin"&variable!="Density"&variable!="Fluoro")

env4$variable <- factor(env4$variable, labels=c("Spd", "Over20", "Temp", "O2", "Trans", "Clay", "Silt", "Sand", "CN", "TOC", "TN", "Por"))

ggplot(data=env4, aes(x=Depth, y=mean, ymin=mean-se, ymax=mean+se, shape=Habitat, linetype=Habitat, colour=Habitat))+
  geom_point(size=5, stroke=1.2)+
  geom_path(size=1)+
  scale_shape_manual(values=c(19,1))+
  geom_errorbar()+
  #stat_smooth(method="lm", formula=y~x, alpha=0.2)+
  scale_linetype_manual(values=c(1,2))+
  scale_colour_manual(values=c("#f1a340", "#998ec3"))+
  labs(x="Depth (m)", y="")+
  facet_wrap(~variable, scales="free_y", ncol=3)+
  theme_bw()%+replace% large
```