---
title: "Macrofauna P/B ratio"
author: "Chih-Lin Wei"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(bbbs)
library(BenthicPro)
library(ggplot2)
library(plyr)
library(doBy)
library(readxl)
library(knitr)

large <- theme(legend.title = element_text(size=20),
        legend.text = element_text(size=20),
        axis.title = element_text(size=20),
        axis.text = element_text(size=20))
rotate <- theme(axis.text.x = element_text(size=20, angle=60, hjust=0.5))

# dark theme for ggplot
dark <- theme(plot.background = element_rect(colour = 'NA', fill = 'gray10'),
        panel.background = element_rect(colour = 'NA', fill = 'transparent'),
        legend.background = element_rect(colour = 'NA', fill = 'transparent'),
        legend.title = element_text(colour = 'white', size=20),
        legend.text = element_text(colour = 'white', size=20),
        axis.title = element_text(colour = 'white', size=20),
        axis.text = element_text(colour = 'white', size=20),
        axis.ticks = element_line(colour = 'white'),
        panel.border = element_rect(fill = 'NA', colour = 'white'), 
        panel.grid.major = element_line(colour = 'gray30'),
        panel.grid.minor = element_line(colour = 'gray20'))
```

# Data preparation

```{r}
dat <- subset(mac, Cruise=="OR1_1096"|Cruise=="OR1_1102"|Cruise=="OR1_1114"|Cruise=="OR1_1126"|Cruise=="OR1_1128"|Cruise=="OR1_1132")
dat.sum <- summaryBy(Wt~Habitat+Cruise+Station+Deployment+Tube+Taxon, data=dat, FUN=c(sum, length))
names(dat.sum)[-1:-6] <- c("Wt", "Count")
dat.sum$Sample.area <- mac$Area[match(with(dat.sum, paste(Cruise, Station)), with(mac, paste(Cruise, Station)))]

# Convert the numbers of polychaete specimen (with head) to abundance
pols <- subset(mac, Taxon=="Polychaeta" & (Condition=="FH" | Condition=="C" | Condition=="FHT"))
pola <- summaryBy(Wt~Habitat+Cruise+Station+Deployment+Tube+Taxon, data=pols, FUN=length, var.names="Count", keep.names = T)
keep <- match(with(pola, paste(Cruise, Station, Deployment, Tube, Taxon)), with(dat.sum, paste(Cruise, Station, Deployment, Tube, Taxon)))
dat.sum$Count[keep] <- pola$Count

# Convert the numbers of complete ophiroid specimens to abundance
ophs <- subset(mac, Taxon=="Ophiuroidea" & Condition=="C")
opha <- summaryBy(Wt~Habitat+Cruise+Station+Deployment+Tube+Taxon, data=ophs, FUN=length, var.names="Count", keep.names = T)
keep <- match(with(opha, paste(Cruise, Station, Deployment, Tube, Taxon)), with(dat.sum, paste(Cruise, Station, Deployment, Tube, Taxon)))
dat.sum$Count[keep] <- opha$Count

# Remove Cyclopoida and Calanoida
dat.sum <- subset(dat.sum, !(Taxon=="Cyclopoida"|Taxon=="Calanoida"))

# Match to marofauna production parameters
dat.sum <- cbind(dat.sum, mpr[match(dat.sum$Taxon, mpr$Taxon), c("ConFac_j2mgwm", "ConFac_j2mgc")])
dat.sum$Bodymass <- with(dat.sum, Wt*ConFac_j2mgwm/Count)
dat.sum <- cbind(dat.sum, env[match(with(dat.sum, paste(Cruise, Station)), with(env, paste(Cruise, Station))), c("Temperature", "Depth")])
dat.sum <- cbind(dat.sum, mpr[match(dat.sum$Taxon, mpr$Taxon), c(-1:-3, -21)])

# Calculate P/B ratio
individualPB<-BenthicPB(dat.sum)
PBresults<-cbind(dat.sum,individualPB)

# annual secondary production in mulligram WM per species and sample per square meter
PBresults$productionWt <- with(PBresults, annual.PtoB*Wt/Sample.area)

# annual secondary production in Joule per species and sample per square meter
PBresults$productionJ <- with(PBresults, productionWt*ConFac_j2mgwm)

# conversion from Joule to milligram carbon per square meter
PBresults$productionC <- with(PBresults, productionJ/ConFac_j2mgc)

# Average P/B ratio by tube
p2b <- summaryBy(Depth+annual.PtoB+lowerCI+upperCI~Habitat+Cruise+Station+Deployment+Tube, data = PBresults, fun = mean, keep.names = TRUE)

# Summation production by tube
pd <- summaryBy(productionWt+productionJ+productionC+Count+Wt~Habitat+Cruise+Station+Deployment+Tube, data = PBresults, fun = sum, keep.names = TRUE)
pd <- cbind(p2b, pd[, -1:-5])

# Remove outlier samples with only 1 individuals
bad <- with(pd, Count <=1 | (Cruise=="OR1_1102" & Station == "GS4") )
dat <- subset(dat, !bad)

se <- function(x) sd(x)/length(x)^0.5
out <- summaryBy(Depth+annual.PtoB+lowerCI+upperCI+productionWt+productionJ+productionC~Habitat+Cruise+Station, data = pd, FUN = c(mean, sd, length, se))

out <- out[, c("Habitat", "Cruise", "Station", "Depth.mean", "annual.PtoB.mean", "lowerCI.mean", "upperCI.mean", "productionWt.mean", "productionWt.se", "productionJ.mean", "productionJ.se", "productionC.mean", "productionC.se", "Depth.length")]

kable(out)
```


```{r, fig.height=5, fig.width=7}
splitBy(~Habitat, out) %>% lapply(FUN=function(x)lm(annual.PtoB.mean~Depth.mean, data=x) %>% summary)

ggplot(data=out, 
       aes(x=Depth.mean, y=annual.PtoB.mean, 
           #ymin=annual.PtoB.mean-lowerCI.mean, ymax=annual.PtoB.mean+upperCI.mean,
           shape=Habitat, colour=Habitat, linetype=Habitat))+
  geom_point(size=5)+
  stat_smooth(method="lm", formula=y~x)+
  #geom_errorbar(linetype=1)+
  scale_colour_manual(values=c("black","gray30"))+
  scale_linetype_manual(values=c(1,2))+
  scale_shape_manual(values=c(19,1))+
  labs(x="Depth (m)", y=expression(P/B~Ratio))+
  theme_bw() %+replace% large #%+replace% dark
```

```{r, fig.height=5, fig.width=7}
splitBy(~Habitat, out) %>% lapply(FUN=function(x)lm(log10(productionWt.mean)~Depth.mean, data=x) %>% summary)

ggplot(data=out, 
       aes(x=Depth.mean, y=log10(productionWt.mean), 
           ymin=log10(productionWt.mean-productionWt.se), ymax=log10(productionWt.mean+productionWt.se),
           shape=Habitat, colour=Habitat, linetype=Habitat))+
  geom_point(size=5)+
  stat_smooth(data=subset(out, Habitat=="Slope"), method="lm", formula=y~x)+
  geom_errorbar(linetype=1)+
  scale_colour_manual(values=c("black","gray30"))+
  scale_linetype_manual(values=c(1,2))+
  scale_shape_manual(values=c(19,1))+
  labs(x="Depth (m)", y=expression(Log[10]~production~(mg~m^-2~yr^-1)))+
  theme_bw() %+replace% large #%+replace% dark
```

```{r, fig.height=5, fig.width=7}
splitBy(~Habitat, out) %>% lapply(FUN=function(x)lm(log10(productionC.mean)~Depth.mean, data=x) %>% summary)

ggplot(data=out, 
       aes(x=Depth.mean, y=log10(productionC.mean), 
           ymin=log10(productionC.mean-productionC.se), ymax=log10(productionC.mean+productionC.se),
           shape=Habitat, colour=Habitat, linetype=Habitat))+
  geom_point(size=5)+
  stat_smooth(data=subset(out, Habitat=="Slope"), method="lm", formula=y~x)+
  geom_errorbar(linetype=1)+
  scale_colour_manual(values=c("black","gray30"))+
  scale_linetype_manual(values=c(1,2))+
  scale_shape_manual(values=c(19,1))+
  labs(x="Depth (m)", y=expression(Log[10]~production~(mgC~m^-2~yr^-1)))+
  theme_bw() %+replace% large #%+replace% dark
```

```{r, fig.height=5, fig.width=7}
splitBy(~Habitat, out) %>% lapply(FUN=function(x)lm(log10(productionJ.mean)~Depth.mean, data=x) %>% summary)

ggplot(data=out, 
       aes(x=Depth.mean, y=log10(productionJ.mean), 
           ymin=log10(productionJ.mean-productionJ.se), ymax=log10(productionJ.mean+productionJ.se),
           shape=Habitat, colour=Habitat, linetype=Habitat))+
  geom_point(size=5)+
  stat_smooth(data=subset(out, Habitat=="Slope"), method="lm", formula=y~x)+
  geom_errorbar(linetype=1)+
  scale_colour_manual(values=c("black","gray30"))+
  scale_linetype_manual(values=c(1,2))+
  scale_shape_manual(values=c(19,1))+
  labs(x="Depth (m)", y=expression(Log[10]~production~(J~m^-2~yr^-1)))+
  theme_bw() %+replace% large #%+replace% dark
```
