---
title: "Meiofauna biomass"
author: "Chih-Lin Wei"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true # table of content true
    toc_depth: 3  # upto three depths of headings (specified by #, ## and ###) 
    toc_float: true
    number_sections: true  ## if you want number sections at each table header
    theme: united  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```

```{r}
library(bbbs)
library(ggplot2)
library(plyr)
library(doBy)
library(readxl)
library(swtmap)
library(maptools)
library(knitr)

large <- theme(legend.title = element_text(size=20),
        legend.text = element_text(size=20),
        axis.title = element_text(size=20),
        axis.text = element_text(size=20))

# dark theme for ggplot
dark <- theme(plot.background = element_rect(colour = 'NA', fill = 'gray10'),
        panel.background = element_rect(colour = 'NA', fill = 'transparent'),
        legend.background = element_rect(colour = 'NA', fill = 'transparent'),
        legend.title = element_text(colour = 'white', size=20),
        legend.text = element_text(colour = 'white', size=20),
        axis.title = element_text(colour = 'white', size=20),
        axis.text = element_text(colour = 'white', size=20),
        axis.ticks = element_line(colour = 'white'),
        panel.border = element_rect(fill = 'NA', colour = 'white'), 
        panel.grid.major = element_line(colour = 'gray30'),
        panel.grid.minor = element_line(colour = 'gray20'))

jet.colors <-colorRampPalette(c("#00007F", "blue", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000"))
```

# Mean density
## Per cruise

```{r, fig.width=7, fig.height=5}
# Sorting data
abun   <- read_excel("../excel/GPSC_meio_sorting_2016.08.18.xlsx", sheet=2)
abun <- summaryBy(Abundance~Cruise+Station+Station+Deployment+Tube+Subcore, data=as.data.frame(abun), FUN=sum, keep.names=T)
abun$Density <- abun$Abundance/(pi*(2.5/2)^2/10000)
dat.mean <- summaryBy(Density~Cruise+Station, data=abun, FUN=c(mean, sd, length), keep.names = TRUE)
dat.mean$Density.se <- dat.mean$Density.sd/dat.mean$Density.length^0.5
cord   <- read_excel("../excel/GPSC_meio_sorting_2016.08.18.xlsx", sheet=1)
keep <- match(paste(dat.mean$Cruise, dat.mean$Station), paste(cord$Cruise, cord$Station))
dat.mean<- cbind(cord[keep, 3:9], dat.mean[, 3:6])
names(dat.mean)[8:11] <- c("Density", "sd", "n", "se")

ggplot(data= dat.mean, 
       aes(x=Depth, y=log10(Density), ymin=log10(Density-se), ymax=log10(Density+se), colour=Habitat, linetype=Habitat, shape=Habitat))+
  geom_point(size=5)+
  scale_shape_manual(values=c(19,1))+
  geom_errorbar(linetype=1)+
  stat_smooth(method="lm", formula=y~x, alpha=0.2)+
  scale_colour_manual(values=c("black","gray30"))+
  scale_shape_manual(values=c(19, 1))+
  scale_linetype_manual(values=c(1,2))+
  labs(x="Depth (m)", y=expression(Log[10]~density~(indiv~m^-2)))+
  #scale_y_log10()+
  theme_bw() %+replace% large

dat.mean$Longitude <- round(dat.mean$Longitude, 4)
dat.mean$Latitude <- round(dat.mean$Latitude, 4)
dat.mean$Depth <- round(dat.mean$Depth, 0)
dat.mean$Density <- round(dat.mean$Density, 0)
dat.mean$sd <- round(dat.mean$sd, 1)
dat.mean$se <- round(dat.mean$se, 1)
kable(dat.mean, align="c")
```

## Per station

```{r, fig.width=7, fig.height=5}
dat.mean.mean <- summaryBy(Density+Longitude+Latitude+Depth~Habitat+Station, data=dat.mean, FUN=c(mean, sd, length))
dat.mean.mean$Density.se <- dat.mean.mean$Density.sd/dat.mean.mean$Density.length^0.5

dat.mean.mean <- dat.mean.mean[,c("Habitat", "Station", "Longitude.mean", "Latitude.mean", "Depth.mean", "Density.length", "Density.mean", "Density.sd", "Density.se")]
names(dat.mean.mean) <- c("Habitat", "Station", "Longitude", "Latitude", "Depth","n", "Density", "sd", "se")

ggplot(data=dat.mean.mean, 
       aes(x=Depth, y=log10(Density), 
           ymin=log10(Density-se), ymax=log10(Density+se),
           colour=Habitat, linetype=Habitat, shape=Habitat))+
  geom_point(size=5)+ 
  stat_smooth(method="lm", formula=y~x)+
  geom_errorbar(linetype=1)+
  scale_colour_manual(values=c("black","gray30"))+
  scale_linetype_manual(values=c(1,2))+
  scale_shape_manual(values=c(19,1))+
  labs(x="Depth (m)", y=expression(Log[10]~density~(ind~m^-2)))+
  theme_bw() %+replace% large #%+replace% dark

dat.mean.mean$Longitude <- round(dat.mean.mean$Longitude, 4)
dat.mean.mean$Latitude <- round(dat.mean.mean$Latitude, 4)
dat.mean.mean$Depth <- round(dat.mean.mean$Depth, 0)
dat.mean.mean$Density <- round(dat.mean.mean$Density, 0)
dat.mean.mean$sd <- round(dat.mean.mean$sd, 1)
dat.mean.mean$sd <- round(dat.mean.mean$se, 1)
kable(dat.mean.mean)
```

# Mean biomass
## Per cruise
```{r, fig.width=7, fig.height=5}
dat.sum <- summaryBy(Wt~Cruise+Station+Deployment+Tube+Subcore, data=mei, FUN=sum, keep.names = TRUE)
dat.sum$Biomass <- dat.sum$Wt/(pi*(2.5/2)^2/10000)
dat.mean <- summaryBy(Biomass~Cruise+Station, data=dat.sum, FUN=c(mean, sd, length), keep.names = TRUE)
dat.mean$Biomass.se <- dat.mean$Biomass.sd/dat.mean$Biomass.length^0.5
keep <- match(paste(dat.mean$Cruise, dat.mean$Station), paste(cord$Cruise, cord$Station))
out <- cbind(cord[keep, 3:9], dat.mean[, 3:6])
names(out) <- c("Habitat",   "Cruise", "Station", "Deployment", "Longitude", "Latitude", "Depth", "Biomass", "sd", "n", "se")

ggplot(data= out, 
       aes(x=Depth, y=log10(Biomass), ymin=log10(Biomass-se), ymax=log10(Biomass+se), colour=Habitat, shape=Habitat, linetype=Habitat))+
  geom_point(size=5)+
  geom_errorbar(linetype=1)+
  stat_smooth(method="lm", formula=y~x, alpha=0.2)+
  scale_colour_manual(values=c("black","gray30"))+
  scale_linetype_manual(values=c(1,2))+
  scale_shape_manual(values=c(19,1))+
  labs(x="Depth (m)", y=expression(Log[10]~biomass~(mg~m^-2)))+
  theme_bw() %+replace% large

out$Longitude <- round(out$Longitude, 4)
out$Latitude <- round(out$Latitude, 4)
out$Depth <- round(out$Depth, 0)
out$Biomass <- round(out$Biomass, 0)
out$sd <- round(out$sd, 1)
out$se <- round(out$se, 1)
kable(out, align="c")
```

## Per station

```{r, fig.width=7, fig.height=5}
dat.mean <- summaryBy(Biomass+Longitude+Latitude+Depth~Region+Habitat+Station, data=out, FUN=c(mean, sd, length))
dat.mean$Biomass.se <- dat.mean$Biomass.sd/dat.mean$Biomass.length^0.5
out <- dat.mean[, c("Habitat", "Station", "Longitude.mean", "Latitude.mean", "Depth.mean", "Biomass.length", "Biomass.mean", "Biomass.sd", "Biomass.se")]
names(out) <- c("Habitat", "Station", "Longitude", "Latitude", "Depth", "n", "Biomass", "sd", "se")

ggplot(data=out, 
       aes(x=Depth, y=log10(Biomass), 
           ymin=log10(Biomass-se), ymax=log10(Biomass+se),
           shape=Habitat, colour=Habitat, linetype=Habitat))+
  geom_point(size=5)+
  stat_smooth(method="lm", formula=y~x)+
  scale_colour_manual(values=c("black","gray30"))+
  scale_shape_manual(values=c(19,1))+
  geom_errorbar(linetype=1)+
  scale_linetype_manual(values=c(1,2))+
  labs(x="Depth (m)", y=expression(Log[10]~biomass~(mg~m^-2)))+
  theme_bw() %+replace% large #%+replace% dark

out$Longitude <- round(out$Longitude, 4)
out$Latitude <- round(out$Latitude, 4)
out$Depth <- round(out$Depth, 0)
out$Biomass <- round(out$Biomass, 0)
out$sd <- round(out$sd, 1)
out$se <- round(out$se, 1)
kable(out, align="c")
```
