---
title: "Sampling Map"
author: "Chih-Lin Wei"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(bbbs)
library(TWBathyMap)
library(doBy)
library(knitr)
library(maptools)
library(rgdal)
```

```{r, fig.width=8, fig.height=8}
e <- extent(119.1, 122.2, 21.6, 25.5)
r <- crop(bathy, e)
r <- projectRaster(r, res=0.001, crs="+proj=longlat")
lon <- c(120.1, 120.1, 120.5, 120.5, 120.1)
lat <- c(22.1, 22.5, 22.5, 22.1, 22.1)
b <- SpatialPolygons(list(Polygons(list(Polygon(cbind(lon, lat))), 1)))

loc <- env[,c("Habitat", "Cruise", "Station", "Longitude", "Latitude", "Depth")]
loc <- summaryBy(Longitude+Latitude+Depth~Habitat+Station, loc, keep.names = TRUE)
coordinates(loc) <- c("Longitude", "Latitude")
projection(loc) <- "+proj=longlat"

tbspplot <- 
  function(x, ...){
  slope <- terrain(x, opt="slope")
  aspect <- terrain(x, opt="aspect")
  hill <- hillShade(slope, aspect, 80, 270)
  p2 <- spplot(hill, col.regions=grey(0:100/100), cut=100, colorkey=FALSE)
  pal <- tb.colors(x)
  p1 <- spplot(x, col.regions=alpha(pal$col, 0.6), at=pal$breaks,
               colorkey=list(space="top", labels=list(cex=1)),
               scales=list(draw = TRUE, cex=0.9)
               ,...)
p1+as.layer(p2, under=T)
}

extra <- function(...){
         panel.levelplot.raster(...)
         sp.points(loc, cex=0.5, pch=19, col=rep(c("#e41a1c", "#4daf4a"), each=4))
         sp.polygons(b, col="#e41a1c", lty=2)
         SpatialPolygonsRescale(layout.scale.bar(), offset=c(119.7, 25), scale = 100/(111.321*cos(22.46*pi/180)), fill = c("white","black"), col = "black")
         sp.text(loc = c(119.7, 25.2), "0")
         sp.text(loc = c(120.7, 25.2), "100 km")
}
tbspplot(r, panel=extra)
```



```{r}
library(swtmap)
e <- extent(120.15, 120.45, 22.1, 22.5)
r <- crop(bathy, e)
r <- projectRaster(r, res=0.0005, crs="+proj=longlat")
```

```{r}


isobath<- rasterToContour(r, levels=seq(-1200, 0, by=200))

extra <- function(...){
         panel.levelplot.raster(...)
         sp.lines(isobath, col="gray30")
         sp.points(loc, cex=2, pch=19, col=rep(c("#e41a1c", "#4daf4a"), each=4))
         sp.pointLabel(loc, labels=loc$Station, allowSmallOverlap=FALSE)
         SpatialPolygonsRescale(layout.scale.bar(), offset=c(120.28, 22.46), scale = 10/(111.321*cos(22.46*pi/180)), fill = c("white","black"), col = "black")
         sp.text(loc = c(120.28, 22.475), "0")
         sp.text(loc = c(120.38, 22.475), "10 km")
}
```


```{r, fig.width=8, fig.height=8}
tbspplot(r, panel=extra)
```

```{r, fig.width=12, fig.height=12}
library(reshape2)
library(ggplot2)
library(viridis)
env2 <- env[, c("Habitat", "Cruise", "Station", "Depth", "Speed.mean", "over20", "Temperature", "Salinity", "Density", "Oxygen", "fluorometer", "transmissometer", "Clay", "Silt", "Sand", "CN",  "TOC", "TN", "Porosity")]

names(env2)[5:19] <- c("Speed", "Over20", "Temperature", "Salin", "Density", "Oxygen", "Fluoro", "Trans", "Clay", "Silt", "Sand", "CN", "TOC", "TN", "Porosity")


se <- function(x)sd(x)/sqrt(length(x))
m <- summaryBy(Depth+Speed+Over20+Temperature+Salin+Density+Oxygen+Fluoro+Trans+Clay+Silt+Sand+CN+TOC+TN+Porosity~Habitat+Station, data=env2, FUN=mean, keep.names = TRUE)
s <-summaryBy(Depth+Speed+Over20+Temperature+Salin+Density+Oxygen+Fluoro+Trans+Clay+Silt+Sand+CN+TOC+TN+Porosity~Habitat+Station, data=env2, FUN=se, keep.names = TRUE)
m <- melt(m, , id.vars=c("Habitat", "Station", "Depth"), measure.vars=c("Speed", "Over20", "Temperature", "Salin", "Density", "Oxygen", "Fluoro", "Trans", "Clay", "Silt", "Sand", "CN", "TOC", "TN", "Porosity"), value.name = "mean")
s <- melt(s, , id.vars=c("Habitat", "Station", "Depth"), measure.vars=c("Speed", "Over20", "Temperature", "Salin", "Density", "Oxygen", "Fluoro", "Trans", "Clay", "Silt", "Sand", "CN", "TOC", "TN", "Porosity"), value.name = "se")


env3 <- cbind(m, se=s$se)

large <- theme(legend.title = element_text(size=20),
        legend.text = element_text(size=20),
        axis.title = element_text(size=20),
        axis.text = element_text(size=20),
        axis.text.x = element_text(angle = 60),
        strip.text= element_text(size=20))


ggplot(data=env3, aes(x=Depth, y=mean, ymin=mean-se, ymax=mean+se, shape=Habitat, linetype=Habitat))+
  geom_point(size=5)+
  geom_path()+
  scale_shape_manual(values=c(19,1))+
  geom_errorbar()+
  #stat_smooth(method="lm", formula=y~x, alpha=0.2)+
  scale_linetype_manual(values=c(1,2))+
  scale_color_viridis(discrete = TRUE)+
  labs(x="Depth (m)", y="")+
  facet_wrap(~variable, scales="free_y", ncol=3)+
  theme_bw()%+replace% large
```

```{r, fig.width=10, fig.height=8}
env4 <- subset(env3, variable!="Salin"&variable!="Density"&variable!="Fluoro")

env4$variable <- factor(env4$variable, labels=c("Spd", "Over20", "Temp", "O2", "Trans", "Clay", "Silt", "Sand", "CN", "TOC", "TN", "Por"))

ggplot(data=env4, aes(x=Depth, y=mean, ymin=mean-se, ymax=mean+se, shape=Habitat, linetype=Habitat))+
  geom_point(size=5)+
  geom_path()+
  scale_shape_manual(values=c(19,1))+
  geom_errorbar()+
  #stat_smooth(method="lm", formula=y~x, alpha=0.2)+
  scale_linetype_manual(values=c(1,2))+
  scale_color_viridis(discrete = TRUE)+
  labs(x="Depth (m)", y="")+
  facet_wrap(~variable, scales="free_y", ncol=3)+
  theme_bw()%+replace% large
```


